[font]
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[window]
opacity = 0.75

# Colors (Root Loops)
# via https://rootloops.sh?sugar=8&colors=9&sogginess=2&flavor=0&fruit=11&milk=0.86

[colors.primary]
background = '#191219'
foreground = '#e9e1e8'

[colors.cursor]
text = '#191219'
cursor = '#b49eb1'

[colors.normal]
black = '#342933'
red = '#fb80aa'
green = '#a1bd22'
yellow = '#f49437'
blue = '#56b8f7'
magenta = '#bd97fc'
cyan = '#28c8b1'
white = '#b49eb1'

[colors.bright]
black = '#635061'
red = '#fda7c1'
green = '#b5d427'
yellow = '#fcb173'
blue = '#89cdfc'
magenta = '#ceb5fd'
cyan = '#30e1c7'
white = '#ddd2dc'
