#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#
# Configuration
# from: https://github.com/mylinuxforwork/dotfiles
font_family                 JetBrainsMono Nerd Font
font_size                   12
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
remember_window_size        no
initial_window_width        950
initial_window_height       500
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
scrollback_lines            2000
wheel_scroll_min_lines      1
enable_audio_bell           no
window_padding_width        10
hide_window_decorations     yes
background_opacity          0.7
dynamic_background_opacity  yes
confirm_os_window_close     0
selection_foreground        none
selection_background        none

# Animated cursor follows text
# include $HOME/.config/ml4w/settings/kitty-cursor-trail.conf

# Include Custom Configuration
# Create the file custom.conf in ~/.config/kitty to overwrite the default configuration
include $HOME/.config/kitty/custom.conf

## Root Loops color scheme
## via https://rootloops.sh?sugar=8&colors=9&sogginess=2&flavor=0&fruit=11&milk=0

# The basic colors
background              #080507
foreground              #f6f2f5
selection_background    #f6f2f5
selection_foreground    #080507

# Cursor colors
cursor_text_color       #080507
cursor                  #b9a4b6

# URL underline color when hovering with mouse
url_color               #fcb173

# Kitty window border colors
active_border_color     #b9a4b6
inactive_border_color   #5d4b5b
bell_border_color       #fb80aa

# Tab bar colors
active_tab_foreground   #f6f2f5
active_tab_background   #080507
inactive_tab_foreground #291f27
inactive_tab_background #b9a4b6
tab_bar_background      #080507

# Colors for marks (marked text in the terminal)
mark1_foreground #f6f2f5
mark1_background #fda7c1
mark2_foreground #f6f2f5
mark2_background #fcb173
mark3_foreground #f6f2f5
mark3_background #b5d427

# The 16 terminal colors

# black
color0 #291f27
color8 #5d4b5b

# red
color1 #fb80aa
color9 #fda7c1

# green
color2  #a1bd22
color10 #b5d427

# yellow
color3  #f49437
color11 #fcb173

# blue
color4  #56b8f7
color12 #89cdfc

# magenta
color5  #bd97fc
color13 #ceb5fd

# cyan
color6  #28c8b1
color14 #30e1c7

# white
color7  #b9a4b6
color15 #e8dfe7

