[bar]
scale = 0.75
bg = "bg-base"
background-opacity = 80
button-variant = "icon-square"
button-bg-opacity = 0

[[bar.layout]]
monitor = "DP-1"
show = true
left = [
    "dashboard",
    "hyprland-workspaces",
    "media",
]
center = ["cava"]
right = [
    "volume",
    "clock",
]

[[bar.layout]]
monitor = "HDMI-A-1"
show = true
left = [
    "idle-inhibit",
    "weather",
    "updates",
]
center = [
    "cpu",
    "ram",
]
right = [
    "systray",
    "notifications",
    "clock",
]

[styling.palette]
primary = "#f6a6bb"

[modules.cava]
bars = 208
framerate = 24
noise-reduction = 0.2345679012345679
bar-width = 7
bar-gap = 0
internal-padding = 0.0

[modules.clock]
format = "%H:%M"
border-show = true

[modules.dashboard]
border-color = "accent"
icon-bg-color = "accent"

[modules.hyprland-workspaces]
app-icons-show = true

[modules.media]
border-show = true
border-color = "accent"
icon-bg-color = "accent"
label-color = "accent"

[modules.notifications]
popup-monitor = "DP-1"

[modules.volume]
border-show = true
border-color = "accent"
icon-bg-color = "accent"
label-color = "accent"

[modules.weather]
location = "Hanover"

[osd]
monitor = "DP-1"

[wallpaper]
engine-enabled = false
